### ISSUE TITLE
Verify the Conditional Branching in Product API GitHub actions workflow

### ISSUE THREAD

**Issue by vishipayyallore** [vishipayyallore/eshop-services-products#2]
Verify the Conditional Branching in Product API GitHub actions workflow

**Description:**
**A.** When we raise the PR, it should execute the build workflow on the PR Branch and **should not** generate the artifacts.
**B.** When the PR is approved, and code gets merged into main. It should run build workflow on the main branch and **generate** the artifacts.

**Comment by vishipayyallore** [comment]
> it is taken to mean please review this file: https://github.com/vishipayyallore/eshop-services-products/actions/runs/1973423195/workflow

@robbiemu 
Apologize for the insufficient information in the description. 
A. When we raise the PR, it should execute the gated build on the PR Branch and should not generate the artifacts.
B. When the PR is approved, and code gets merged into main. It should run build on Main branch and generate the artifacts.

**Regards,
Swamy**

**Comment by robbiemu** [comment]
https://github.com/vishipayyallore/eshop-services-products/runs/5537545581?check_suite_focus=true

verified not publishing artifact on PR.

**Comment by robbiemu** [comment]
suggestion:

https://github.com/vishipayyallore/eshop-services-products/actions/runs/1980695836/workflow in this workflow, we are running analysis on PR, then again on push to main (completion of main branch change). I want to be sure we want those details both times.. it seems like you might only want this for completed prs
